import './globals.css'
import ChakraProv from '~/helpers/chakra'
import QuerysClient from '~/helpers/querysClient.jsx'
import {colorsUi} from '~/ui/colors.js'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="fr">
      <body style={{background: colorsUi.white2}}>
        <QuerysClient>
          <ChakraProv>{children}</ChakraProv>
        </QuerysClient>
      </body>
    </html>
  )
}
